/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.24 from the
 * contents of Catalog.xs. Do not edit this file, edit Catalog.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Catalog.xs"
/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License, Version 1.0 only
 * (the "License").  You may not use this file except in compliance
 * with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */
/*
 * Copyright 2002 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 *
 * Catalog.xs contains XS code for exacct catalog tag manipulation.  This
 * consists of code to create the @_Constants array and %_Constants hash used
 * for defining constants on the fly via AUTOLOAD, and utility functions for
 * creaing double-typed SVs.
 */

#pragma ident	"%Z%%M%	%I%	%E% SMI"

#include "../exacct_common.xh"

/* Pull in the file generated by extract_defines. */
#include "CatalogDefs.xi"

/*
 * This function populates the %_Constants hash and @_Constants array based on
 * the values extracted from the exacct header files by the extract_defines
 * script and written to the .xi file which is included above.  It also creates
 * a const sub for each constant that returns the associcated value.  It should
 * be called from the BOOT section of this module.  The structure of the
 * %_Constants hash is given below - this is used to map between the symbolic
 * and numeric values of the various EX[CTD] constants.  The register() method
 * extends the %_Constants hash with values for the foreign catalog, so that it
 * can be handled in exactly the same way as the built-in catalog.
 *
 * $Constants{catlg}{name}{EXC_DEFAULT} => 0
 *                  ...
 *                  {value}{0} => 'EXC_DEFAULT'
 *                  ...
 *                           *A*
 *           {id}{name}{EXD}{name}{EXD_CREATOR} => 3
 *                          ...
 *                          {value}{3} => 'EXD_CREATOR'
 *                          ...
 *               {value}{0} => *A*
 *               ...
 *           {other}{name}{EXC_CATALOG_MASK} => 251658240
 *                  ...
 *                  {value}{251658240} => 'EXC_CATALOG_MASK'
 *                  ...
 *           {type}{name}{EXT_DOUBLE} => 1342177280
 *                 ...
 *                 {value}{1342177280} => 'EXT_DOUBLE'
 *                 ...
 */
#define	CONST_NAME "::Catalog::_Constants"
static void
define_catalog_constants()
{
	HV		*const_hash, *hv1, *hv2, *hv3;
	AV		*const_ary;
	HV		*type_by_name,  *type_by_value;
	HV		*catlg_by_name, *catlg_by_value;
	HV		*id_by_name,    *id_by_value;
	HV		*other_by_name, *other_by_value;
	constval_t	*cvp;

	/* Create the two new perl variables. */
	const_hash = perl_get_hv(PKGBASE CONST_NAME, TRUE);
	const_ary = perl_get_av(PKGBASE CONST_NAME, TRUE);

	/* Create the 'type' subhash. */
	type_by_name = newHV();
	type_by_value = newHV();
	hv1 = newHV();
	hv_store(const_hash, "type", 4, newRV_noinc((SV*)hv1), 0);
	hv_store(hv1, "name", 4, newRV_noinc((SV*)type_by_name), 0);
	hv_store(hv1, "value", 5, newRV_noinc((SV*)type_by_value), 0);

	/* Create the 'catlg' subhash. */
	catlg_by_name = newHV();
	catlg_by_value = newHV();
	hv1 = newHV();
	hv_store(const_hash, "catlg", 5, newRV_noinc((SV*)hv1), 0);
	hv_store(hv1, "name", 4, newRV_noinc((SV*)catlg_by_name), 0);
	hv_store(hv1, "value", 5, newRV_noinc((SV*)catlg_by_value), 0);

	/*
	 * The 'id' subhash has an extra level of name/value subhashes,
	 * where the upper level is indexed by the catalog prefix (EXD for
	 * the default catalog).  The lower two levels are actually the same
	 * hashes referenced by two parents, and hold the catalog id numeric
	 * values and corresponding string values.
	 */
	id_by_name = newHV();
	id_by_value = newHV();
	hv1 = newHV();
	hv_store(const_hash, "id", 2, newRV_noinc((SV*)hv1), 0);
	hv2 = newHV();
	hv_store(hv1, "name", 4, newRV_noinc((SV*)hv2), 0);
	hv3 = newHV();
	hv_store(hv2, "EXD", 3, newRV_noinc((SV*)hv3), 0);
	hv_store(hv3, "name", 4, newRV_noinc((SV*)id_by_name), 0);
	hv_store(hv3, "value", 5, newRV_noinc((SV*)id_by_value), 0);
	IdValueHash = newHV();
	hv_store(hv1, "value", 5, newRV_noinc((SV*)IdValueHash), 0);
	hv_store_ent(IdValueHash, newSVuv(EXC_DEFAULT), newRV_inc((SV*)hv3), 0);

	/* Create the 'other' subhash, for non-catalog #defines. */
	other_by_name = newHV();
	other_by_value = newHV();
	hv1 = newHV();
	hv_store(const_hash, "other", 5, newRV_noinc((SV*)hv1), 0);
	hv_store(hv1, "name", 4, newRV_noinc((SV*)other_by_name), 0);
	hv_store(hv1, "value", 5, newRV_noinc((SV*)other_by_value), 0);

	/*
	 * Populate %_Constants and %_Constants from the contents of the
	 * generated constants array.
	 */
	for (cvp = constants; cvp->name != NULL; cvp++) {
		HV	*name_hv, *value_hv;
		SV	*name, *value;

		/* Create the name/value SVs, save the name in @_Constants. */
		name = newSVpvn((char *)cvp->name, cvp->len);
		value = newSVuv(cvp->value);
		av_push(const_ary, SvREFCNT_inc(name));

		/*
		 * Decide which hash the name/value belong in,
		 * based on consttype .
		 */
		switch (cvp->consttype) {
		case type:
			name_hv  = type_by_name;
			value_hv = type_by_value;
			break;
		case catlg:
			name_hv = catlg_by_name;
			/* Special case for duplicated-value EXC_NONE tag. */
			if (cvp->value == EXC_NONE &&
			    strcmp(cvp->name, "EXC_NONE") == 0) {
				value_hv = NULL;
			} else {
				value_hv = catlg_by_value;
			}
			break;
		case id:
			name_hv  = id_by_name;
			value_hv = id_by_value;
			break;
		case other:
			name_hv  = other_by_name;
			value_hv = other_by_value;
			break;
		}

		/* Store in the appropriate name & value hashes. */
		if (name_hv) {
			hv_store_ent(name_hv, name, value, 0);
		}
		if (value_hv) {
			hv_store_ent(value_hv, value, name, 0);
		}

		/* Free the name and/or value if they weren't used. */
		if (! name_hv) {
			SvREFCNT_dec(value);
		}
		if (! value_hv) {
			SvREFCNT_dec(name);
		}
	}
}
#undef CONST_NAME

/*
 * The XS code exported to perl is below here.  Note that the XS preprocessor
 * has its own commenting syntax, so all comments from this point on are in
 * that form.
 *
 * All the following are private functions.
 */

#line 210 "Catalog.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 352 "Catalog.c"

XS_EUPXS(XS_Sun__Solaris__Exacct__Catalog__double_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Exacct__Catalog__double_type)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "i, c");
    {
	unsigned int	i = (unsigned int)SvUV(ST(0))
;
	char *	c = (char *)SvPV_nolen(ST(1))
;
	SV *	RETVAL;
#line 218 "Catalog.xs"
	RETVAL = newSVuv(i);
	sv_setpv(RETVAL, c);
	SvIOK_on(RETVAL);
#line 370 "Catalog.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Exacct__Catalog__is_iv); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Exacct__Catalog__is_iv)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    {
	SV *	sv = ST(0)
;
	int	RETVAL;
	dXSTARG;
#line 231 "Catalog.xs"
	RETVAL = SvIOK(sv);
#line 391 "Catalog.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Exacct__Catalog__is_pv); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Exacct__Catalog__is_pv)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    {
	SV *	sv = ST(0)
;
	int	RETVAL;
	dXSTARG;
#line 242 "Catalog.xs"
	RETVAL = SvPOK(sv);
#line 411 "Catalog.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Exacct__Catalog__new_catalog); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Exacct__Catalog__new_catalog)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    {
	SV *	sv = ST(0)
;
	SV *	RETVAL;
#line 253 "Catalog.xs"
	RETVAL = new_catalog(SvUV(sv));
#line 430 "Catalog.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Exacct__Catalog__catalog_value); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Exacct__Catalog__catalog_value)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    {
	SV *	sv = ST(0)
;
	int	RETVAL;
	dXSTARG;
#line 264 "Catalog.xs"
	RETVAL = catalog_value(sv);
#line 451 "Catalog.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Sun__Solaris__Exacct__Catalog); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Sun__Solaris__Exacct__Catalog)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Sun::Solaris::Exacct::Catalog::_double_type", XS_Sun__Solaris__Exacct__Catalog__double_type, file, "$$");
        (void)newXSproto_portable("Sun::Solaris::Exacct::Catalog::_is_iv", XS_Sun__Solaris__Exacct__Catalog__is_iv, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Exacct::Catalog::_is_pv", XS_Sun__Solaris__Exacct__Catalog__is_pv, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Exacct::Catalog::_new_catalog", XS_Sun__Solaris__Exacct__Catalog__new_catalog, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Exacct::Catalog::_catalog_value", XS_Sun__Solaris__Exacct__Catalog__catalog_value, file, "$");

    /* Initialisation Section */

#line 207 "Catalog.xs"
	init_stashes();
	define_catalog_constants();

#line 489 "Catalog.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

