#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          kdr_transport
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Short-Description: kdr transport
# Description:       kronometrix data recording transport
### END INIT INFO
#
# chkconfig: 2345 96 10
# description: kronometrix data recording transport
#
# /etc/init.d/kdr_transport
#
#  Copyright (c) 2020 Stefan Parvu (www.kronometrix.org).
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#  (http://www.gnu.org/copyleft/gpl.html)


RETVAL=0
OS_NAME=`uname -s`

BASEDIR="/opt/kronometrix/etc"
KRMX_SVC="${BASEDIR}/transport"
KRMX_USER="krmx"

# basedir test
test -d ${BASEDIR} || exit 0
test -f ${KRMX_SVC} || exit 0


start() {
    su - $KRMX_USER -c "${KRMX_SVC} start"
}


stop() {
    su - $KRMX_USER -c "${KRMX_SVC} stop"
}


status() {
    su - $KRMX_USER -c "${KRMX_SVC} status"
}

case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      stop
      start
      ;;
   status)
      status
      ;;
   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
esac
exit $RETVAL

