.TH xenrec 1  "$Date: 2014-04-27 #$" "USER COMMANDS"
.SH NAME
xenrec \- Xen Hypervisor Recorder. Uses perl
.SH SYNOPSIS
.B xenrec
[-hvV] [-d domain[,domain...]] | [interval [count]]

.SH DESCRIPTION
xenrec records per Xen domain statistics:
domain state, cpu usage in seconds, cpu usage in percentage,
current memory, current memory in percentage, maximum domain memory 
stats, in KB and many others.

.PP
The recorder uses xentop utility to fetch all metrics. A system running
Xen Hypervisor should have by default xentop installed. If the utility 
is not found xenrec will not run. The raw data is already prepared and 
formatted for SDR analysis process. The recorder runs continuously.

.SH OS
Linux 2.6+

.SH OPTIONS
.SS
\-d domain,...
monitor one or many interfaces with a specific name

.SS
\-h
print help information
.SS
\-v
print verbose information
.SS
\-V
print revision information
.SS
interval
interval in seconds between each sample
.SS
count
number of samples

.PP
.SH EXAMPLES
.SS xenrec 5
monitor all found domains every 5 seconds 

.SS xenrec -d Domain-0 5 10
monitor Domain-0, 10 times sampled every 5 seconds

.PP
.SH FIELDS
.TP
#1 timestamp
the time in seconds since Epoch

.TP
#2 name
domain name, the guest domU name

.TP
#3 state
domain state: blocked (b), dying (d), shutdown (s) crashed (c), paused (p), running (r) 

.TP
#4 cputime
displays cpu usage in seconds

.TP
#5 cpupct
displays cpu usage in percentage

.TP
#6 mem
current memory

.TP
#7 mempct
current memory in percentage

.TP
#8 maxmem
maximum domain memory stats, in KB

.TP
#9 maxmempct
memory stats in percentage, ratio of current domain memory to total node memory 

.TP
#10 vpus
number of virtual processing units, vCPUs

.TP
#11 nets
number of virtual networks

.TP
#12 nettx
data transmission rate in KB 

.TP
#13 netrx
data receiving rate in KB

.TP
#14 vbds
total number of virtual block devices in the domain

.TP
#15 vbdoo
total number of VBD OO requests

.TP
#16 vbdrd
VBD read rate

.TP
#17 vbdwr
VBD write rate

.TP
#18 vbdrsect
VBD read sectors rate

.TP
#19 vbdwsect
VBD write sectors rate

.TP
#20 ssid
domain security id

.PP
.SH NOTES
This recorder does not support interval values lower than 2 seconds !  

.PP
xenrec records 20 Xen Hypervisor metrics on x64 and x86 platforms !


.PP
.SH DOCUMENTATION
See SDR documentation for more details.
.SH EXIT
xenrec will run continuously until is stopped by the master script 
or manually stopped. 

.SH AUTHOR
Stefan Parvu
.SH SEE ALSO
perl(1)
