/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.24 from the
 * contents of Privilege.xs. Do not edit this file, edit Privilege.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Privilege.xs"
/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License, Version 1.0 only
 * (the "License").  You may not use this file except in compliance
 * with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */
/*
 * Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 *
 * Privilege.xs contains XS wrappers for the process privilege maniplulation
 * functions.
 */

#pragma ident	"%Z%%M%	%I%	%E% SMI"

/* Solaris includes. */
#include <priv.h>
#include <ctype.h>

/* Perl includes. */
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#define	IVCONST(s, c)	newCONSTSUB(s, #c, newSViv((int)c));
#define	POFF		(sizeof ("PRIV_") - 1)

#define	RETPRIVSET(set)		\
	ST(0) = sv_newmortal();						\
	sv_setref_pv(ST(0), "Sun::Solaris::Privilege::PrivsetPtr",	\
	    (void*)(set));						\
	SvREADONLY_on(SvRV(ST(0)))

typedef int sysret;

typedef priv_set_t Sun__Solaris__Privilege__Privset;

static priv_set_t *
dupset(const priv_set_t *s)
{
	priv_set_t *new = priv_allocset();
	if (new == NULL)
		return (NULL);

	priv_copyset(s, new);
	return (new);
}

/*
 * Automatically derive the #define constant from the constant value.
 * This is the uppercase value of the constant with "PRIV_" prepended.
 * The (name, value) pair computed in that way is stored twice:
 * 	once as constant subroutine in the module's hash table.
 *	once as (key, value) in a hash table.
 */

static void
PRIVconst(HV *sym, HV *var, const char *name)
{
	char upname[128];
	ssize_t len;
	int i;

	len = snprintf(upname, sizeof (upname), "PRIV_%s", name);
	if (len >= sizeof (upname))
		return;

	for (i = POFF; i < len; i++)
		upname[i] = toupper(upname[i]);
	newCONSTSUB(sym, upname, newSVpv(name, len - POFF));
	hv_store(var, upname, len, newSVpv(name, len - POFF), 0);
}

/*
 * The XS code exported to perl is below here.  Note that the XS preprocessor
 * has its own commenting syntax, so all comments from this point on are in
 * that form.
 *
 * Inside perl, privilege sets are represented as expanded strings;
 * privileges and privilege sets are only known by name.
 */

#line 109 "Privilege.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 251 "Privilege.c"

XS_EUPXS(XS_Sun__Solaris__Privilege_getppriv); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_getppriv)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "which");
    {
	const char *	which = (const char *)SvPV_nolen(ST(0))
;
	Sun__Solaris__Privilege__Privset *	RETVAL;
#line 151 "Privilege.xs"
	RETVAL = priv_allocset();
	if (getppriv(which, RETVAL) != 0) {
		priv_freeset(RETVAL);
		XSRETURN_UNDEF;
	} else {
		RETPRIVSET(RETVAL);
	}
#line 271 "Privilege.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_setppriv); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_setppriv)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "op, which, set");
    {
	int	op = (int)SvIV(ST(0))
;
	const char *	which = (const char *)SvPV_nolen(ST(1))
;
	Sun__Solaris__Privilege__Privset *	set;
	sysret	RETVAL;

	if (SvROK(ST(2)) && sv_derived_from(ST(2), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(2)));
	    set = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::setppriv",
			"set", "Sun::Solaris::Privilege::PrivsetPtr")
;

	RETVAL = setppriv(op, which, set);
	ST(0) = sv_newmortal();
	{
		if (RETVAL != -1) {
			if (RETVAL == 0)
				sv_setpvn(ST(0), "0 but true", 10);
			else
				sv_setiv(ST(0), (IV)RETVAL);
		}
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_emptyset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_emptyset)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Sun__Solaris__Privilege__Privset *	RETVAL;
#line 168 "Privilege.xs"
	RETVAL = priv_allocset();
	if (RETVAL == NULL) {
		XSRETURN_UNDEF;
	}
	priv_emptyset(RETVAL);
	RETPRIVSET(RETVAL);
#line 331 "Privilege.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_fillset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_fillset)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Sun__Solaris__Privilege__Privset *	RETVAL;
#line 178 "Privilege.xs"
	RETVAL = priv_allocset();
	if (RETVAL == NULL) {
		XSRETURN_UNDEF;
	}
	priv_fillset(RETVAL);
	RETPRIVSET(RETVAL);
#line 352 "Privilege.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_isemptyset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_isemptyset)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "set");
    {
	Sun__Solaris__Privilege__Privset *	set;
	boolean_t	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    set = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_isemptyset",
			"set", "Sun::Solaris::Privilege::PrivsetPtr")
;

	RETVAL = priv_isemptyset(set);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_isfullset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_isfullset)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "set");
    {
	Sun__Solaris__Privilege__Privset *	set;
	boolean_t	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    set = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_isfullset",
			"set", "Sun::Solaris::Privilege::PrivsetPtr")
;

	RETVAL = priv_isfullset(set);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_isequalset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_isequalset)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "set1, set2");
    {
	Sun__Solaris__Privilege__Privset *	set1;
	Sun__Solaris__Privilege__Privset *	set2;
	boolean_t	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    set1 = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_isequalset",
			"set1", "Sun::Solaris::Privilege::PrivsetPtr")
;

	if (SvROK(ST(1)) && sv_derived_from(ST(1), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    set2 = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_isequalset",
			"set2", "Sun::Solaris::Privilege::PrivsetPtr")
;

	RETVAL = priv_isequalset(set1, set2);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_issubset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_issubset)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "set1, set2");
    {
	Sun__Solaris__Privilege__Privset *	set1;
	Sun__Solaris__Privilege__Privset *	set2;
	boolean_t	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    set1 = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_issubset",
			"set1", "Sun::Solaris::Privilege::PrivsetPtr")
;

	if (SvROK(ST(1)) && sv_derived_from(ST(1), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    set2 = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_issubset",
			"set2", "Sun::Solaris::Privilege::PrivsetPtr")
;

	RETVAL = priv_issubset(set1, set2);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_ismember); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_ismember)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "set, priv");
    {
	Sun__Solaris__Privilege__Privset *	set;
	const char *	priv = (const char *)SvPV_nolen(ST(1))
;
	boolean_t	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    set = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_ismember",
			"set", "Sun::Solaris::Privilege::PrivsetPtr")
;

	RETVAL = priv_ismember(set, priv);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_ineffect); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_ineffect)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "priv");
    {
	const char *	priv = (const char *)SvPV_nolen(ST(0))
;
	boolean_t	RETVAL;
	dXSTARG;

	RETVAL = priv_ineffect(priv);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_intersect); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_intersect)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "set1, set2");
    {
	Sun__Solaris__Privilege__Privset *	set1;
	Sun__Solaris__Privilege__Privset *	set2;
	Sun__Solaris__Privilege__Privset *	RETVAL;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    set1 = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_intersect",
			"set1", "Sun::Solaris::Privilege::PrivsetPtr")
;

	if (SvROK(ST(1)) && sv_derived_from(ST(1), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    set2 = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_intersect",
			"set2", "Sun::Solaris::Privilege::PrivsetPtr")
;
#line 217 "Privilege.xs"
	RETVAL = dupset(set2);
	if (RETVAL == NULL) {
		XSRETURN_UNDEF;
	}
	priv_intersect(set1, RETVAL);
	RETPRIVSET(RETVAL);
#line 578 "Privilege.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_union); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_union)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "set1, set2");
    {
	Sun__Solaris__Privilege__Privset *	set1;
	Sun__Solaris__Privilege__Privset *	set2;
	Sun__Solaris__Privilege__Privset *	RETVAL;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    set1 = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_union",
			"set1", "Sun::Solaris::Privilege::PrivsetPtr")
;

	if (SvROK(ST(1)) && sv_derived_from(ST(1), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    set2 = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_union",
			"set2", "Sun::Solaris::Privilege::PrivsetPtr")
;
#line 229 "Privilege.xs"
	RETVAL = dupset(set2);
	if (RETVAL == NULL) {
		XSRETURN_UNDEF;
	}
	priv_union(set1, RETVAL);
	RETPRIVSET(RETVAL);
#line 621 "Privilege.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_inverse); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_inverse)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "set1");
    {
	Sun__Solaris__Privilege__Privset *	set1;
	Sun__Solaris__Privilege__Privset *	RETVAL;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    set1 = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_inverse",
			"set1", "Sun::Solaris::Privilege::PrivsetPtr")
;
#line 240 "Privilege.xs"
	RETVAL = dupset(set1);
	if (RETVAL == NULL) {
		XSRETURN_UNDEF;
	}
	priv_inverse(RETVAL);
	RETPRIVSET(RETVAL);
#line 653 "Privilege.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_addset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_addset)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "set, priv");
    {
	Sun__Solaris__Privilege__Privset *	set;
	const char *	priv = (const char *)SvPV_nolen(ST(1))
;
	sysret	RETVAL;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    set = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_addset",
			"set", "Sun::Solaris::Privilege::PrivsetPtr")
;

	RETVAL = priv_addset(set, priv);
	ST(0) = sv_newmortal();
	{
		if (RETVAL != -1) {
			if (RETVAL == 0)
				sv_setpvn(ST(0), "0 but true", 10);
			else
				sv_setiv(ST(0), (IV)RETVAL);
		}
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_copyset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_copyset)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "set1");
    {
	Sun__Solaris__Privilege__Privset *	set1;
	Sun__Solaris__Privilege__Privset *	RETVAL;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    set1 = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_copyset",
			"set1", "Sun::Solaris::Privilege::PrivsetPtr")
;
#line 257 "Privilege.xs"
	RETVAL = dupset(set1);
	if (RETVAL == NULL) {
		XSRETURN_UNDEF;
	}
	RETPRIVSET(RETVAL);
#line 721 "Privilege.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_delset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_delset)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "set, priv");
    {
	Sun__Solaris__Privilege__Privset *	set;
	const char *	priv = (const char *)SvPV_nolen(ST(1))
;
	sysret	RETVAL;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    set = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_delset",
			"set", "Sun::Solaris::Privilege::PrivsetPtr")
;

	RETVAL = priv_delset(set, priv);
	ST(0) = sv_newmortal();
	{
		if (RETVAL != -1) {
			if (RETVAL == 0)
				sv_setpvn(ST(0), "0 but true", 10);
			else
				sv_setiv(ST(0), (IV)RETVAL);
		}
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_getbynum); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_getbynum)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "i");
    {
	int	i = (int)SvIV(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = priv_getbynum(i);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_getsetbynum); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_getsetbynum)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "i");
    {
	int	i = (int)SvIV(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = priv_getsetbynum(i);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_set_to_str); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_set_to_str)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "s, c, f");
    {
	Sun__Solaris__Privilege__Privset *	s;
	char	c = (char)*SvPV_nolen(ST(1))
;
	int	f = (int)SvIV(ST(2))
;
	char *	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Sun::Solaris::Privilege::PrivsetPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    s = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Sun::Solaris::Privilege::priv_set_to_str",
			"s", "Sun::Solaris::Privilege::PrivsetPtr")
;

	RETVAL = priv_set_to_str(s, c, f);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
#line 283 "Privilege.xs"
	free(RETVAL);
#line 831 "Privilege.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_str_to_set); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_str_to_set)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "buf, sep");
    {
	const char *	buf = (const char *)SvPV_nolen(ST(0))
;
	const char *	sep = (const char *)SvPV_nolen(ST(1))
;
	Sun__Solaris__Privilege__Privset *	RETVAL;
#line 290 "Privilege.xs"
	RETVAL = priv_str_to_set(buf, sep, NULL);
	if (RETVAL == NULL) {
		XSRETURN_UNDEF;
	}
	RETPRIVSET(RETVAL);
#line 855 "Privilege.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_priv_gettext); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_priv_gettext)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "priv");
    {
	const char *	priv = (const char *)SvPV_nolen(ST(0))
;
	char *	RETVAL;
	dXSTARG;

	RETVAL = priv_gettext(priv);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
#line 300 "Privilege.xs"
	free(RETVAL);
#line 877 "Privilege.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_setpflags); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_setpflags)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "flag, val");
    {
	uint_t	flag = (uint_t)SvIV(ST(0))
;
	uint_t	val = (uint_t)SvIV(ST(1))
;
	sysret	RETVAL;

	RETVAL = setpflags(flag, val);
	ST(0) = sv_newmortal();
	{
		if (RETVAL != -1) {
			if (RETVAL == 0)
				sv_setpvn(ST(0), "0 but true", 10);
			else
				sv_setiv(ST(0), (IV)RETVAL);
		}
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege_getpflags); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege_getpflags)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "flag");
    {
	uint_t	flag = (uint_t)SvIV(ST(0))
;
	sysret	RETVAL;

	RETVAL = getpflags(flag);
	ST(0) = sv_newmortal();
	{
		if (RETVAL != -1) {
			if (RETVAL == 0)
				sv_setpvn(ST(0), "0 but true", 10);
			else
				sv_setiv(ST(0), (IV)RETVAL);
		}
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Sun__Solaris__Privilege__PrivsetPtr_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Sun__Solaris__Privilege__PrivsetPtr_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "ps");
    {
	Sun__Solaris__Privilege__Privset *	ps;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    ps = INT2PTR(Sun__Solaris__Privilege__Privset *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not a reference",
			"Sun::Solaris::Privilege::PrivsetPtr::DESTROY",
			"ps")
;
#line 317 "Privilege.xs"
	priv_freeset(ps);
#line 957 "Privilege.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Sun__Solaris__Privilege); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Sun__Solaris__Privilege)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Sun::Solaris::Privilege::getppriv", XS_Sun__Solaris__Privilege_getppriv, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::setppriv", XS_Sun__Solaris__Privilege_setppriv, file, "$$$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_emptyset", XS_Sun__Solaris__Privilege_priv_emptyset, file, "");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_fillset", XS_Sun__Solaris__Privilege_priv_fillset, file, "");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_isemptyset", XS_Sun__Solaris__Privilege_priv_isemptyset, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_isfullset", XS_Sun__Solaris__Privilege_priv_isfullset, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_isequalset", XS_Sun__Solaris__Privilege_priv_isequalset, file, "$$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_issubset", XS_Sun__Solaris__Privilege_priv_issubset, file, "$$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_ismember", XS_Sun__Solaris__Privilege_priv_ismember, file, "$$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_ineffect", XS_Sun__Solaris__Privilege_priv_ineffect, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_intersect", XS_Sun__Solaris__Privilege_priv_intersect, file, "$$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_union", XS_Sun__Solaris__Privilege_priv_union, file, "$$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_inverse", XS_Sun__Solaris__Privilege_priv_inverse, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_addset", XS_Sun__Solaris__Privilege_priv_addset, file, "$$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_copyset", XS_Sun__Solaris__Privilege_priv_copyset, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_delset", XS_Sun__Solaris__Privilege_priv_delset, file, "$$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_getbynum", XS_Sun__Solaris__Privilege_priv_getbynum, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_getsetbynum", XS_Sun__Solaris__Privilege_priv_getsetbynum, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_set_to_str", XS_Sun__Solaris__Privilege_priv_set_to_str, file, "$$$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_str_to_set", XS_Sun__Solaris__Privilege_priv_str_to_set, file, "$$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::priv_gettext", XS_Sun__Solaris__Privilege_priv_gettext, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::setpflags", XS_Sun__Solaris__Privilege_setpflags, file, "$$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::getpflags", XS_Sun__Solaris__Privilege_getpflags, file, "$");
        (void)newXSproto_portable("Sun::Solaris::Privilege::PrivsetPtr::DESTROY", XS_Sun__Solaris__Privilege__PrivsetPtr_DESTROY, file, "$");

    /* Initialisation Section */

#line 109 "Privilege.xs"
{
	HV *stash;
	HV *privs;
	HV *privsets;
	const char *p;
	int i;

	stash = gv_stashpv("Sun::Solaris::Privilege", TRUE);

	/*
	 * Global constants
	 */
	IVCONST(stash, PRIV_STR_PORT);
	IVCONST(stash, PRIV_STR_LIT);
	IVCONST(stash, PRIV_STR_SHORT);
	IVCONST(stash, PRIV_ALLSETS);
	IVCONST(stash, PRIV_DEBUG);
	IVCONST(stash, PRIV_AWARE);
	IVCONST(stash, PRIV_ON);
	IVCONST(stash, PRIV_OFF);
	IVCONST(stash, PRIV_SET);

	/*
	 * %PRIVILEGES hash and the privilege constants
	 */
	privs = perl_get_hv("Sun::Solaris::Privilege::PRIVILEGES", TRUE);
	for (i = 0; (p = priv_getbynum(i++)) != NULL; )
		PRIVconst(stash, privs, p);

	/*
	 * %PRIVSETS hash and the privset constants
	 */
	privsets = perl_get_hv("Sun::Solaris::Privilege::PRIVSETS", TRUE);
	for (i = 0; (p = priv_getsetbynum(i++)) != NULL; )
		PRIVconst(stash, privsets, p);
}

#line 1047 "Privilege.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

