#!/bin/sh

# initial installation, after tasks
chown -R krmx:krmx /opt/kronometrix || :

if [ ! -L /etc/init.d/kdr_agents ]; then
    ln -s /opt/kronometrix/etc/rc/kdr_agents /etc/init.d/kdr_agents || :
fi

if [ ! -L /etc/init.d/kdr_transport ]; then
    ln -s /opt/kronometrix/etc/rc/kdr_transport /etc/init.d/kdr_transport || :
fi

# link here kdr
update-rc.d kdr_agents start 20 2 3 4 5 . stop 20 0 1 6 . >/dev/null 2>&1 || :

# link here kdr.transport
update-rc.d kdr_transport start 20 2 3 4 5 . stop 20 0 1 6 . >/dev/null 2>&1 || :

if [ -d /opt/kronometrix ]; then
    chown -R krmx:krmx /opt/kronometrix/log || :
fi
/etc/init.d/kdr_agents start >/dev/null 2>&1 || :
/etc/init.d/kdr_transport start >/dev/null 2>&1 || :

# cronjobs
if [ -f /etc/cron.allow ]; then
    if ! grep krmx /etc/cron.allow >/dev/null; then
        echo "krmx" >> /etc/cron.allow 2>/dev/null || :
    fi
fi

crontab -u krmx -l > /var/tmp/cronkrmx 2>/dev/null || :
echo "59 23 * * *  /bin/sleep 59 && /usr/sbin/logrotate -f -s /opt/kronometrix/log/logkrmx.status /opt/kronometrix/etc/logrotate.krmx" >> /var/tmp/cronkrmx || :
echo "00 00 * * *  /bin/sleep 30 && /opt/kronometrix/bin/raw2day" >> /var/tmp/cronkrmx || :
crontab -u krmx /var/tmp/cronkrmx 2>/dev/null || :

# restore config
if [ -f /opt/kronometrix/backup/kronometrix.json ]; then
    cp /opt/kronometrix/backup/kronometrix.json /opt/kronometrix/etc || :
fi

