#!/bin/sh

# initial installation, after tasks
chown -R krmx:krmx /opt/kronometrix || :

if [ ! -L /etc/init.d/kdr ]; then
    ln -s /opt/kronometrix/etc/rc/kdr /etc/init.d/kdr || :
fi

if [ ! -L /etc/init.d/kdr_transport ]; then
    ln -s /opt/kronometrix/etc/rc/kdr_transport /etc/init.d/kdr_transport || :
fi

# link here kdr
update-rc.d kdr start 20 2 3 4 5 . stop 20 0 1 6 . >/dev/null 2>&1 || :

# link here kdr.transport
update-rc.d kdr_transport start 20 2 3 4 5 . stop 20 0 1 6 . >/dev/null 2>&1 || :

if [ -d /opt/kronometrix ]; then
    chown -R krmx:krmx /opt/kronometrix/log || :
fi
/etc/init.d/kdr start >/dev/null 2>&1 || :

# cronjobs
if [ -f /etc/cron.allow ]; then
    if ! grep krmx /etc/cron.allow >/dev/null; then
        echo "krmx" >> /etc/cron.allow 2>/dev/null || :
    fi
fi

crontab -u krmx -l > /var/tmp/cronkrmx 2>/dev/null || :
echo "59 23 * * *  /bin/sleep 59 && /usr/sbin/logrotate -f -s /opt/kronometrix/log/logkrmx.status /opt/kronometrix/etc/logrotate.krmx" >> /var/tmp/cronkrmx || :
echo "00 00 * * *  /bin/sleep 30 && /opt/kronometrix/bin/raw2day" >> /var/tmp/cronkrmx || :
crontab -u krmx /var/tmp/cronkrmx 2>/dev/null || :

# restore config
if [ -f /opt/kronometrix/backup/kronometrix.json ]; then
    cp /opt/kronometrix/backup/kronometrix.json /opt/kronometrix/etc || :
fi

/opt/kronometrix/bin/actmsg | grep web >/dev/null 2>&1
if [ $? -eq 0 ]; then
    if [ -f /opt/kronometrix/backup/webrec.json ]; then
        cp /opt/kronometrix/backup/webrec.json /opt/kronometrix/etc || :
    fi
fi

/opt/kronometrix/bin/actmsg | grep svc >/dev/null 2>&1
if [ $? -eq 0 ]; then
    if [ -f /opt/kronometrix/backup/svcrec.json ]; then
        cp /opt/kronometrix/backup/svcrec.json /opt/kronometrix/etc || :
    fi
fi

/opt/kronometrix/bin/actmsg | grep http >/dev/null 2>&1
if [ $? -eq 0 ]; then
    if [ -f /opt/kronometrix/backup/httprec.json ]; then
        cp /opt/kronometrix/backup/httprec.json /opt/kronometrix/etc || :
    fi
fi

# start transport
/etc/init.d/kdr_transport start >/dev/null 2>&1 || :

# udev rules
if [ ! -f /etc/udev/rules.d/41-kronometrix.rules ]; then
    echo "ATTRS{idVendor}==\"1941\", ATTRS{idProduct}==\"8021\", SUBSYSTEMS==\"usb\", ACTION==\"add\", MODE=\"0666\", GROUP=\"krmx\"" > /etc/udev/rules.d/41-kronometrix.rules || :
fi
