#!/bin/sh

# echo "preinst: preparing to install package"
# initial installation
if [ -f /etc/init.d/kdr_agents ]; then
    /etc/init.d/kdr_agents stop >/dev/null 2>&1 || :
fi

if [ -f /etc/init.d/kdr_transport ]; then
        /etc/init.d/kdr_transport stop >/dev/null 2>&1 || :
fi

if ! getent group krmx >/dev/null; then
        groupadd -g 5000 krmx || :
fi

if ! getent passwd krmx >/dev/null; then
    useradd -u 5000 -g krmx -d /home/krmx -m krmx || :
fi

if [ ! -d /opt/kronometrix ]; then
    mkdir /opt/kronometrix || :
fi

