#!/bin/sh

# make a copy of kronometrix.json
if [ -f /opt/kronometrix/etc/kronometrix.json ]; then
    if [ ! -d /opt/kronometrix/backup ]; then
        mkdir /opt/kronometrix/backup
    fi
    cp /opt/kronometrix/etc/kronometrix.json /opt/kronometrix/backup || :
fi

# make a copy of webrec.json svcrec.json
/opt/kronometrix/bin/actmsg | grep web >/dev/null 2>&1
if [ $? -eq 0 ]; then
    if [ -f /opt/kronometrix/etc/webrec.json ]; then
        if [ ! -d /opt/kronometrix/backup ]; then
            mkdir /opt/kronometrix/backup
        fi
        cp /opt/kronometrix/etc/webrec.json /opt/kronometrix/backup || :
    fi
fi

/opt/kronometrix/bin/actmsg | grep svc >/dev/null 2>&1
if [ $? -eq 0 ]; then
    if [ -f /opt/kronometrix/etc/svcrec.json ]; then
        if [ ! -d /opt/kronometrix/backup ]; then
            mkdir /opt/kronometrix/backup
        fi
        cp /opt/kronometrix/etc/svcrec.json /opt/kronometrix/backup || :
    fi
fi

update-rc.d -f kdr_agents remove >/dev/null 2>&1 || : 
update-rc.d -f kdr_transport remove >/dev/null 2>&1 || :

# check for old installs
if [ -f /etc/init.d/kdr_transport ]; then
    /etc/init.d/kdr_transport stop >/dev/null 2>&1 || :
    update-rc.d -f kdr_transport remove >/dev/null 2>&1 || :
    rm -f /etc/init.d/kdr_transport || :
fi

# uninstall
if [ -f /etc/init.d/kdr_agents ]; then
    /etc/init.d/kdr_agents stop >/dev/null 2>&1 || :
    rm -f /etc/init.d/kdr_agents || :
fi

if [ -f /etc/init.d/kdr_transport ]; then
    /etc/init.d/kdr_transport stop >/dev/null 2>&1 || :
    rm -f /etc/init.d/kdr_transport || :
fi

# wipeout krmx crontab
crontab -u krmx -r  2>/dev/null || :
