#!/bin/sh

RC_CONF=/etc/rc.conf


if [ "X$2" == "XPRE-INSTALL" ]; then
    if ! /usr/sbin/pw groupshow krmx >/dev/null 2>&1; then
        /usr/sbin/pw groupadd krmx -g 5000
    fi

    if ! /usr/sbin/pw usershow krmx >/dev/null 2>&1; then
        /usr/sbin/pw useradd krmx -m -d /home/krmx \
         -u 5000 -g 5000 -c "Kronometrix user"
    fi
fi

if [ "X$2" == "XPOST-INSTALL" ]; then

    # setup crontabs
    if ! grep krmx /etc/cron.allow >/dev/null 2>&1; then
        echo "krmx" >> /etc/cron.allow
    fi

    if [ ! -f /var/cron/tabs/krmx ]; then
        echo "59 23 * * *  /bin/sleep 59 && newsyslog -f /etc/newsyslog.conf.d/kronometrix" >> /var/cron/tabs/krmx
        echo "00 00 * * *  /bin/sleep 30 && /opt/kronometrix/bin/raw2day" >> /var/cron/tabs/krmx
    fi

    # restore config
    if [ -f /opt/kronometrix/backup/kronometrix.json ]; then
        cp /opt/kronometrix/backup/kronometrix.json /opt/kronometrix/etc
    fi

    chown -R krmx:krmx /opt/kronometrix

    # install kornometrix service
    grep "^kronometrix_enable" ${RC_CONF} >/dev/null 2>&1
    if [ $? -eq 1 ]; then

        # add the service
        echo "kronometrix_enable=\"YES\"" >> ${RC_CONF}
        if [ $? -eq 1 ]; then
            echo "Error: cannot activate service: kronometrix, exit now"
            exit 1
        fi
    fi

    grep "^kronometrix_user" ${RC_CONF} >/dev/null 2>&1 
    if [ $? -eq 1 ]; then
        echo "kronometrix_user=\"krmx\"" >> ${RC_CONF}
        if [ $? -eq 1 ]; then
            echo "Error: cannot activate service: kronometrix_user, exit now"
            exit 1
        fi
    fi

    grep "^kronometrix_transport_enable" ${RC_CONF} >/dev/null 2>&1
    if [ $? -eq 1 ]; then

        # add the service
        echo "kronometrix_transport_enable=\"YES\"" >> ${RC_CONF}
        if [ $? -eq 1 ]; then
            echo "Error: cannot activate service: kronometrix_transport, exit now"
            exit 1
        fi
    fi

    # start and link the service
    if [ ! -L /etc/rc.d/kronometrix ]; then
        ln -s /opt/kronometrix/etc/rc/kronometrix /etc/rc.d/kronometrix
    fi

    if [ ! -L /etc/rc.d/kronometrix_transport ]; then
        ln -s /opt/kronometrix/etc/rc/kronometrix_transport /etc/rc.d/kronometrix_transport
    fi

    /etc/rc.d/kronometrix onestart >/dev/null
fi
