#!/bin/sh

if [ "X$2" == "XDEINSTALL" ]; then
    /etc/rc.d/kronometrix_transport onestop >/dev/null 2>&1
    /etc/rc.d/kronometrix onestop >/dev/null 2>&1

    # make a copy of kronometrix.json
    if [ -f /opt/kronometrix/etc/kronometrix.json ]; then
        if [ ! -d /opt/kronometrix/backup ]; then
            mkdir /opt/kronometrix/backup
        fi
        cp /opt/kronometrix/etc/kronometrix.json /opt/kronometrix/backup
    fi

    chown -R krmx:krmx /opt/kronometrix/backup
fi

if [ "X$2" == "XPOST-DEINSTALL" ]; then

    [ -L /etc/rc.d/kronometrix_transport ] && rm /etc/rc.d/kronometrix_transport 
    [ -L /etc/rc.d/kronometrix ] && rm /etc/rc.d/kronometrix

    # uninstall service
    SVC=kronometrix
    RC_CONF=/etc/rc.conf
    DATE=`date +"%Y%m%d_%H%M%S"`

    # operate on date snapshot file
    cp ${RC_CONF} ${RC_CONF}.${DATE}

    grep "^${SVC}_transport_enable=\"YES\"" ${RC_CONF}.${DATE} >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        # remove the service
        grep -v "^${SVC}_transport_enable=\"YES\"" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}.${DATE}
    fi

    grep "^${SVC}_user=\"krmx\"" ${RC_CONF}.${DATE} >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        # remove the service
        grep -v "^${SVC}_user=\"krmx\"" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}.${DATE}
    fi

    grep "^${SVC}_enable=\"YES\"" ${RC_CONF} >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        # remove the service
        grep -v "^${SVC}_enable=\"YES\"" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}.${DATE}
    fi

    # remove the temp rc.conf
    mv ${RC_CONF}.${DATE} ${RC_CONF}
    if [ $? -eq 1 ]; then
        echo "Error: cannot uninstall service: ${SVC}, exit now"
        exit 1
    fi

    # remove crontab
    yes | crontab -u krmx -r >/dev/null 2>&1

fi
